Repository liquality/liquality-sdk-demo, pull requests merged in 2023-02, with the labels that each got.

#2 fix: integrate getNfts
  package-lock.json
  package.json
  src/components/Collectibles/NftImages.tsx
  src/noImage.png
  src/pages/Collectibles.tsx
  src/setupSDK.ts
Labels: 🔍 Ready for Review, size/M

#4 Feat/auth logic
  package.json
  src/App.js
  src/Dat
  src/DataContext.js
  src/DataContext.ts
  src/components/Auth/CreateWallet.tsx
  src/components/Auth/DisplayWalletValues.tsx
  src/components/Auth/SignIn.tsx
  src/pages/Auth.tsx
  src/pages/Home.js
Labels: 🔍 Ready for Review, size/L

#6 add dropdown menu
  src/App.css
  src/components/Navbar.js
  src/pages/Home.js
Labels: 🔍 Ready for Review, size/XL

#7 fix: integrate swap
  package-lock.json
  package.json
  src/components/Collectibles/MintERC1155Form.tsx
  src/components/Collectibles/MintERC721Form.tsx
  src/components/Collectibles/NewERC1155CollectionForm.tsx
  src/components/Collectibles/NewERC721CollectionForm.tsx
  src/components/Collectibles/TransferNftsForm.tsx
  src/pages/Swap.js
  src/pages/Swap.tsx
Labels: 🔍 Ready for Review, size/L
